//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneToOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGuardian
    {
        public int R_no { get; set; }
        public int G_no { get; set; }
        public string G_Name { get; set; }
    
        public virtual TblStudent TblStudent { get; set; }
    }
}
