//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneToOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public int R_no { get; set; }
        public string Std_Name { get; set; }
        public string Std_Phn { get; set; }
        public string Std_Email { get; set; }
        public string CNIC { get; set; }
    
        public virtual TblGuardian TblGuardian { get; set; }
    }
}
